[theme]
base = "dark"
backgroundColor = "#0a1118"
secondaryBackgroundColor = "#152534"
textColor = "#f1f5f9"
primaryColor = "#E21A6B"
font = "sans serif"

[server]
headless = true
enableCORS = false

[browser]
gatherUsageStats = false
